### ISSUE TITLE
SillyTavern 1.12.6 'release' 中好像无法修改音色了

### ISSUE THREAD

**Issue by 1015g** [v3ucn/GPT-SoVITS-V2#2]
SillyTavern 1.12.6 'release' &TTS v1.0.0 中好像无法修改音色了，在TTS中选择对应参考音频之后并没有改变
![QQ截图20241109010520](https://github.com/user-attachments/assets/7332f5bd-db29-459e-9197-35ddb4587920)

**Comment by 1015g** [comment]
![QQ截图20241109010736](https://github.com/user-attachments/assets/539157bf-9bca-4708-9e5a-0a6183fc7f23)

**Comment by v3ucn** [comment]
选择 GPT-SoVITS-V2 ，你选的xtts

**Comment by 1015g** [comment]
> 选择 GPT-SoVITS-V2 ，你选的xtts

老大，如果有这个选项我肯定不选这个啊 ，关键只能选XTTS
![image](https://github.com/user-attachments/assets/78db096c-cff4-4f19-83f5-43030421197e)

**Comment by v3ucn** [comment]
> @v3ucn 大佬？Please help me！

1.12.7官方合并了分支，有了 俩个新的选项
